### PR TITLE
Updated all dependencies to the latest version.

### LINKED ISSUE #3: Please upgrade reqwest to at least version 0.11
I'm using this library with tokio 1.2.0 and I'm getting build errors because of mismatching versions.

### PR DESCRIPTION
**Pull request by anlumo**
Fixes #3.

### CODE REVIEW

**Comment by opax7** [comment]
@tritone11 is this project still active? Are you open to help with maintaining? Curious to understand where in the lifecycle this project is for you.

**Comment by tritone11** [comment]
@opax7  yes this project is still alive but not mantained, yes I  am open for a help maintaining as I have no time currently

**Comment by opax7** [comment]
Hey @tritone11, I would be happy to help if you are open to it. I could start with publishing a new version of the crate if you want to grant me access to do so. Let me know.

**Comment by opax7** [comment]
@tritone11, just bumping you on this. I would like to help maintaining this project and would like to use a published crate with the latest fix in place. Let me know if I can help and what you might need. Otherwise, if you could publish the latest merge to master to crates.io, it would be greatly appreciated.

**Comment by anlumo** [comment]
@opax7 I got owner permissions for crates.io, so I can do it as well now. I'm just also pretty busy at the moment, but I can take a look later on.

**Comment by opax7** [comment]
Thanks so much @anlumo

**Comment by opax7** [comment]
A gentle bump on this @anlumo. Please let me know if I should approach this in some other way. Thanks!

**Comment by anlumo** [comment]
Sorry for the delay, I just published a new version!

**Comment by opax7** [comment]
Super cool! Thanks a million.

**Pull request merged**
