### PR TITLE
Update to Rust 2018

### PR DESCRIPTION
**Pull request by anlumo**
Hi,

I don't know how interested you are in this, but I updated your crate to use Rust 2018, all the most recent versions of the dependencies and ran rustfmt on all files.

I also changed all functions to return `Result`s instead of panicing on error and made them async.

### CODE REVIEW

**Comment by tritone11** [comment]
Hi @anlumo,
thanks a lot for working on this, looks good to me!
I am gonna look at it better later and merge it. Could you also bump the version to 0.0.5?

**Comment by anlumo** [comment]
Done. Note that I'm currently working on adding the user representation API (`admin/realms/{realm-name}/users/{id}`), since I need that for my project.

**Comment by tritone11** [comment]
That's great! I have in plan to remove reqwest and substitute it with surf and async_std later in time, as all my project is using that

**Comment by tritone11** [comment]
Ok it looks good in my environment, only problem, the jsonwebtoken dependency cause a lot of conflicts with other crates that use the ring crate, when a different version of ring is used.
  
However, this is related to how the jsonwebtoken crate is, so I will merge it and will remove jsonwebtoken in the future.

**Pull request merged**
